auct/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import hollau.views

urlpatterns = [
    url(r'^', include('hollau.urls')),
    url(r'^admin/', admin.site.urls),
]

hollau/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    # url(r'^$', views.main, name='main'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^home/$', views.home),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add_lot/$', views.add_lot, name='add_lot'),
    url(r'^lot_edit/(?P<pk>[0-9]+)/$', views.lot_edit, name='lot_edit'),
    url(r'^lot_detail/(?P<pk>[0-9]+)/$', views.lot_detail, name='lot_detail'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^section_check/$', views.section_check, name='section_check'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^make_bet/$', views.make_bet, name='make_bet'),
    url(r'^my_bets/$', views.my_bets, name='my_bets'),
    url(r'^my_lots/$', views.my_lots, name='my_lots'),
    url(r'^test_form/$', views.test_form, name='test_form'),
    url(r'^test_ajax/$', views.test_ajax, name='tets_ajax'),
    url(r'^countdown/$', views.countdown, name='countdown'),
    url(r'^test_check/$', views.test_check, name='test_check'),
    url(r'^check_update/$', views.check_update, name='check_update'),
    url(r'^testpagination/$', views.testpagination, name='testpagination'),
    url(r'^adress/$', views.adress_form, name='adress'),
    url(r'^myprofile/$', views.user_profile, name='userprofile'),
]

hollau/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
import datetime


class UserProfile(models.Model):
    user = models.ForeignKey(User, related_name='profile')
    first_name = models.CharField(u'имя', max_length=50, null=True)
    last_name = models.CharField(u'фамилия', max_length=50, null=True)
    email = models.EmailField(u'электронный адрес', null=True)
    photo = models.TextField(null=True)
    phonenumber = models.CharField(u'номер телефона', max_length=20, default=None, null=True)
    userlocation = models.CharField(u'местоположение', max_length=100, default=None, null=True)


class Category(models.Model):
    name = models.CharField(u'категория', max_length=30)

    def __unicode__(self):
        return self.name


class Lot(models.Model):
    name = models.CharField(u"предложение", max_length=100)
    description = models.TextField(u"описание предложения")
    # photo = models.ImageField(u"фотография", blank=True, upload_to='%Y-%m-%d')
    start_price = models.FloatField(u"стартовая цена")
    current_price = models.FloatField(u"текущая цена", blank=True, null=True)
    sold = models.BooleanField(u"продано", default=False)
    author = models.ForeignKey(User, verbose_name=u"Аукционатор", related_name='lots', default="1")
    start_date = models.DateTimeField(u'начало продажи', auto_now_add=True)
    end_date = models.DateTimeField(u'окончание продажи')
    lastest_propose = models.DateTimeField(u'последнее предложение', blank=True, null=True)
    category = models.ForeignKey(Category, verbose_name=u'категория', default=1)
    location = models.CharField(u'локация', max_length=100, default='')

    class Admin:
        list_display = ("name", "price", "propose", "lastest_propose", "bought")
        ordering = ("-lastest_propose", "end_date",)

    def __unicode__(self):
        return self.name

    # class Meta:
    #     verbose_name = u'Лот'
    #     verbose_name_plural = u'Лоты'

    def propose(self):
        lastest = self.propose_set.order_by('-date')
        if lastest:
            return lastest[0]
        else:
            return None

    def bought(self):
        return self.propose() and ((self.end_date < datetime.datetime.now()) or self.sold)

    def get_end_date(self):
        return datetime.datetime.strftime(self.end_date, "%d.%m.%y, %H:%M")


class Bet(models.Model):
    lot = models.ForeignKey(Lot, verbose_name=u'лот')
    date = models.DateTimeField(u'дата', auto_now=True, editable=False)
    price = models.FloatField(u"новая цена")
    person = models.ForeignKey(User)

    class Admin:
        list_display = ("lot", "price")

    class Meta:
        verbose_name = u"Ставка"
        verbose_name_plural = u"Ставки"

    def __unicode__(self):
        return self.person.username

    def get_date(self):
        return datetime.datetime.strftime(self.date, "%d.%m.%y, %H:%M")

hollau/forms.py
# -*- coding: utf-8 -*-

from hollau.models import UserProfile, Lot, Bet, User, Category
from django import forms


class Lot(forms.ModelForm):
    class Meta:
        model = Lot
        fields = ['name', 'description', 'start_price', 'end_date', 'category', 'location']

class UserProfile(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user']

class CategoryAdd(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class Bet(forms.ModelForm):
    class Meta:
        model = Bet
        fields = ['price']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ('is_staff', 'is_active', 'is_superuser', 'last_login', 'date_joined', 'groups', 'user_permissions',
                   'password')

class TestForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)

class AdressForm(forms.Form):
    adress = forms.CharField(label='adress', max_length=100)

hollau/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render

# Create your views here.

from django.shortcuts import render_to_response, redirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template.context import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hollau import models
import json as simplejson
from hollau import forms
from django.http import Http404
import datetime


def index(request):
    return HttpResponse('You are welcome to hollau site!')


def login(request):
    print request.user.id
    return render_to_response('login.html', {'user': request.user})


@login_required(login_url='/')
def home(request):
    return render_to_response('home.html', {'user': request.user})


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/login')

@login_required(login_url='/')
def user_profile(request):
    print request.user.first_name
    print request.user.last_name
    print request.user.email
    try:
        userq = models.UserProfile.objects.get(user=request.user)
        print 'in try'
    except ObjectDoesNotExist:
        print 'in except'
        userq = models.UserProfile.objects.create(user=request.user, first_name=request.user.first_name, last_name=request.user.last_name, email = request.user.email)
    if request.method == 'GET':
        print userq.first_name
        print userq.last_name
        print userq.email
        print userq.user.first_name
        categories = models.Category.objects.all()
        return render(request, 'userprofile.html', {'form':forms.UserProfile(initial={
            'first_name':userq.first_name, 
            'last_name':userq.last_name, 
            'email':userq.email,
            'phonenumber':userq.phonenumber,
            'userlocation':userq.userlocation,
        }), 
                                                    'categories': categories, 
                                                    'message':False})
                                                    
    elif request.method == 'POST':
        categories = models.Category.objects.all()
        form = forms.UserProfile(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            first_name=data['first_name']
            last_name=data['last_name']
            email=data['email']
            phonenumber=data['phonenumber']
            userlocation=data['userlocation']
            models.UserProfile.objects.update(user=request.user, first_name=first_name, last_name=last_name, email = email, phonenumber=phonenumber, userlocation=userlocation)
            return render(request, 'userprofile.html', {'form':forms.UserProfile(initial={
                'first_name':first_name, 
                'last_name':last_name, 
                'email':email, 
                'phonenumber':phonenumber, 
                'userlocation':userlocation
            }),
                'categories': categories, 
                'message':True
            })
            
    
def add_lot(request):
    if request.method == 'POST':
        form = forms.Lot(request.POST)
        # print request.user.id
        # print dir(request.session)
        if form.is_valid():
            data = form.cleaned_data
            name = data['name']
            description = data['description']
            start_price = data['start_price']
            # start_date = data['start_date']
            end_date = data['end_date']
            category = data['category']
            location = data['location']
            models.Lot.objects.create(
                name=name,
                description=description,
                start_price=start_price,
                # start_date=start_date,
                end_date=end_date,
                author=request.user,
                category=category,
                location=location,
            )
            return HttpResponse('Ok')
        else:
            return HttpResponse('NOK')
    else:
        context = {}
        categories = models.Category.objects.all()
        return render(request, 'add_lot_form.html', {'form': forms.Lot, 'categories': categories})


def section_check(request):
    section = request.GET.get('section')
    print section
    section_qw = models.Category.objects.get(name__icontains=section[1:-2].lower())
    if section == section_qw.lower():
        value = section
    else:
        value = (1, 2, 3)
    data = {'value': value}
    print data
    return JsonResponse(data)


def add_category(request):
    if request.method == 'GET':
        categories = models.Category.objects.all()
        return render(request, 'addcategory.html', {'form': forms.CategoryAdd(), 'categories': categories})
    else:
        form = forms.CategoryAdd(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            category_name = data['name']

            try:
                models.Category.objects.get(name=category_name)
            except ObjectDoesNotExist:
                models.Category.objects.create(name=category_name)
        return render(request, 'addcategory.html', {'form': forms.CategoryAdd(), 'categories': categories})


def lot_edit(request, pk):
    try:
        lot = models.Lot.objects.get(pk=pk)
    except ObjectDoesNotExist:
        return HttpResponse('No such lot')
    if request.user == lot.author:
        if request.method == 'GET':
            return render(request, 'editLot.html', {'form': forms.Lot(instance=lot), 'pk': pk
                                                    })
        else:
            form = forms.Lot(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                lot.name = data['name']
                lot.description = data['description']
                lot.start_price = data['start_price']
                # lot.start_date = data['start_date']
                lot.end_date = data['end_date']
                lot.save()
                return HttpResponse('Your lot was edited')
    else:
        return HttpResponse("You can't edit this lot")


def lot_detail(request, pk):
    print request.user
    lot = models.Lot.objects.get(pk=pk)
    bets = models.Bet.objects.filter(lot=lot).order_by('-price')
    can_bet = (request.user != lot.author)
    categories = models.Category.objects.all()
    if bets.last():
        betuser = bets.last().person.first_name
    else:
        betuser = None
    return render(request, 'lot_detail.html', {'lot': lot, 'betuser': betuser, 'pk': pk, 'can_bet': can_bet,
                                               'categories': categories})


def category(request, pk):
    categories = models.Category.objects.all()
    category_lots = models.Lot.objects.filter(category=pk).order_by('-start_date')
    paginator, page = paginate(request, category_lots)
    return render(request, 'categorypage.html', {'paginator': paginator, 'page': page, 'category_lots': page.object_list, 'categories': categories, 'category_id': pk})


def my_bets(request):
    user = request.user
    my_bet_lots = models.Bet.objects.filter(person=user)
    categories = models.Category.objects.all()
    my_lots = [my_bet.lot for my_bet in my_bet_lots]
    paginator, page = paginate(request, my_lots)
    return render(request, 'my_lot.html', {'paginator': paginator, 'page': page, 'my_lots': page.object_list, 'categories': categories})


def my_lots(request):
    my_lots = models.Lot.objects.filter(author=request.user)
    categories = models.Category.objects.all()
    paginator, page = paginate(request, my_lots)
    return render(request, 'my_lot.html', {'paginator': paginator, 'page': page, 'my_lots': page.object_list, 'categories': categories})


def make_bet(request):
    pk = request.GET.get('pk')
    lot = models.Lot.objects.get(pk=pk)
    print request.user
    if request.user != lot.author and request.user.is_authenticated and lot.end_date > datetime.datetime.now():
        print 'ok'
        if not lot.current_price:
            lot.current_price = 0.9 * lot.start_price
        else:
            lot.current_price = 0.9 * lot.current_price
        bet = models.Bet.objects.create(lot=lot, price=lot.current_price, person=request.user)
        lot.save()
        data = {'current_price': lot.current_price, 'betuser':bet.person.first_name}
    else:
        data = {'current_price': None}
    return JsonResponse(data)


def test_form(request):
    if request.method == 'GET':
        return render(request, 'test.html', {})
    else:
        return HttpResponse('ok')


def test_ajax(request):
    username = request.GET.get('username', None)
    if username == 'Art'.lower():
        boolVal = True
    else:
        boolVal = False
    data = {
        'is_taken': boolVal
    }
    return JsonResponse(data)


def countdown(request):
    return render(request, 'countdown.html', {})


def test_check(request):
    if request.method == 'GET':
        return render(request, 'autocheck.html', {})


def check_update(request):
    pk = request.GET.get('pk')
    lot = models.Lot.objects.filter(pk=pk).get()
    bet = models.Bet.objects.filter(lot=lot).order_by('-date').first()
    if bet is not None: 
        data = {'exist': True,'end_date': lot.end_date, 'current_price': lot.current_price, 'bet': bet.date}
    else:
        data = {'exist': False}
    return JsonResponse(data)


def paginate(request, qs):
    try:
        limit = int(request.GET.get('limit', 6))
    except ValueError:
        limit = 6
    if limit > 6:
        limit = 6
    try:
        page = int(request.GET.get('page',1))
    except ValueError:
        raise Http404
    paginator = Paginator(qs, limit)
    try:
        page = paginator.page(page)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

hollau/templates/add_lot_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block javascript %}
	<link rel="stylesheet" type="text/css" href="/static/datetimepicker/jquery.datetimepicker.css"/>
	<script type="text/javascript" src="/static/script_section.js"></script>
	<script src="https://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<script src="{% static 'js/jquery.geocomplete.js' %}"></script>
	<script src="{% static 'js/geoposition.js' %}"></script>
	<script src="{% static 'js/userlocation.js' %}"></script>
	<script src="{% static 'js/logger.js' %}"></script>
	<link rel="stylesheet" href="{% static 'mycss.css' %}"/>
	
{% endblock %}

{% block content %}
<div class="row" id='biglotblock'>
<div class="col-sm-4 sides"></div>	
<div class="col-sm-4 portfolio-item blockview wrapper_body">
<div class="cbm_wrap">


  <form method="post" action="{% url 'add_lot' %}">
  	<div class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
	<pre id="logger" hidden="true">Log:</pre>
    <div>
	<button type='submit' id="makeabet" class="btn">Добавить лот</button>
	</div>
	<div>
  </form>

<script src="/static/datetimepicker/jquery.js"></script>
<script src="/static/datetimepicker/jquery.datetimepicker.full.js"></script>
<script>
    $("[id='id_start_date']").each(function (){ 
   		$(this).attr("id", "date1");
	});
    $("[id='id_end_date']").each(function (){ 
   		$(this).attr("id", "date2");
	});
    
</script>
<script src="/static/datetimepicker/datetime.js"></script>
</<div>
</<div>
</<div>
</<div>	
{% endblock %}

hollau/templates/addcategory.html
{% extends 'base.html' %}
{% block javascript %}

{% endblock %}
{% block content %}
	{% for category in categories %}
<p>{{category}}</p>
	{% endfor %}
  <form method="post" action="{% url 'add_category' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить категорию</button>
  </form>
<br>
{% endblock %}

hollau/templates/adress_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block javascript %}
	<link rel="stylesheet" type="text/css" href="/static/jquery.countdown.css">
	<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<script src="{% static 'js/jquery.geocomplete.js' %}"></script>
	<script src="{% static 'js/geoposition.js' %}"></script>
	

{% endblock %}

{% block content %}
  <form method="post" action="{% url 'adress' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Добавить адрес</button>
  </form>
<br>
{% endblock %}

hollau/templates/autocheck.html
<html>  
<head>  
<meta http-equiv="Content-Type" content="text/html; Charset=UTF-8">  
<!--<script type="text/javascript" src="jquery.js"></script>-->  
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
</head>  
  
<body>  
    <p id = "lot_id">10</p>
    
    <form action="{% url 'test_form'%}" method="post">
	{% csrf_token %}
    <input type="text" name="username" id="test_username" value="" />
    <p id = "help_message"></p>
    
    <div id="content"></div>  
      
    <script>  
        
        function show()  
        {  
            //var lot_id = $("#lot_id").text();
            
            console.log('in show')
            $.ajax({  
                url: '/check_update/',
                data: {
          			'lot_id': lot_id
        		},
                cache: false,  
                success: function(html){  
                    $("#content").html(html);  
                }  
            });  
        }  
      
        $(document).ready(function(){  
            show();  
            setInterval('show()',1000);  
        });  
    </script>  
      
</body>  
</html>

hollau/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Шаблон Bootstrap 101</title>
    <!-- Bootstrap -->
    <link href={% static "bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
    <link href={% static 'offcanvas.css' %} rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'mycss.css' %} " />
    
    
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-latest.js"></script>
    <script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
    
    

    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Project: HOLLAU</a>
        </div>
        
        <div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
            
            {%if user.is_authenticated%}
            <li><a href="#">{{user.first_name}}</a></li>
            
            <li id="lots" class="active"><a href="#">Мои лоты</a></li>
            <li id="bets"><a href="#about">Мои ставки</a></li>
            <li id="ownlot"><a href="{% url 'add_lot' %}">Создать лот</a></li>
            <li><a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
            <li><a href="{%url 'login' %}">Друг</a></li>
            <li><a href="{% url 'login' %}">Войти</a></li>
            {% endif %}
          </ul>
        </div><!-- /.nav-collapse -->
        
        
        
        
        
      </div><!-- /.container -->
      
      
      
      <div class="container-fluid" id='header'>
      <div class="col-xs-4" id='serviceabout'>  
      <a href="#">О сервисе</a>
      </div>
      <div class="col-xs-4">
      </div>
      
      
      <div id="dd"  class="wrapper-dropdown-5 col-xs-4" tabindex="1">
        
        <p>Категории</p>
        <ul class="dropdown">
        {% for category in categories %}
          <li><a href="{% url 'category' category.id%}" class="list-group-item">{{ category.name }}</a></li>
        {% endfor %}
        </ul>
        
      </div>
      
      
      </div><!-- /.container -->
      
      
      
    </nav><!-- /.navbar -->



    
    <section id="portfolio">
        <div class="container">
            
            {% block content %}{% endblock %}
            
        </div>
    </section>
    
      
    {% block javascript %}{% endblock %}
<script src={% static "js/offcanvas.js" %}></script>
<script type="text/javascript">

			function DropDown(el) {
				this.dd = el;
				this.initEvents();
			}
			DropDown.prototype = {
				initEvents : function() {
					var obj = this;

					obj.dd.on('click', function(event){
						$(this).toggleClass('active');
						event.stopPropagation();
					});	
				}
			}

			$(function() {

				var dd = new DropDown( $('#dd') );

				$(document).click(function() {
					// all dropdowns
					$('.wrapper-dropdown-5').removeClass('active');
				});

			});

		</script>
  </body>
</html>

hollau/templates/categorypage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block javascript %}
		<meta charset="utf-8" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" />
        <link rel="stylesheet" href="{% static 'countdown_style.css' %}" />
        <link rel="stylesheet" href="{% static 'jquery.countdown.css' %} " />
        <link rel="stylesheet" href="{% static 'freelancer.min.css' %} " />
        <link rel="stylesheet" href="{% static 'mycss.css' %} " />
		<!--<script src="{% static 'js/makeabet.js' %}"></script>-->
		<script src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
		<script src="{% static 'js/jquery.countdown.js' %}"></script>
		<script src="{% static 'js/countdown_2.js' %}"></script>
		<!--<script src="{% static 'js/countdown.js' %}"></script>-->
		<script src="{% static 'js/makeabet_2.js' %}"></script>
		<script src="{% static 'js/update_data.js' %}"></script>

{% endblock %}

{% block content %}
<div class="row" id='biglotblock'>
  {% for lot in category_lots %}
  <div class="col-sm-4 portfolio-item blockview wrapper_body">

<div class="cbm_wrap">

<div id='lotblock' data-timer="{{lot.end_date|date:'Y/m/d H:i'}}">
  
<p id = "pk" hidden="true">{{lot.id}}</p>

<div id='contdiv'>

<div id='firstblock' class="col-xs-8">
<div id='lotname'>
<p class="shortdescription"><a href="{% url 'lot_detail' lot.id%}">{{lot.name}}</a></p>
<p>Лот {{lot.id}}</p>
</div> <!--div lotname-->
<br>
<div id='lotdescription' >
<p>Описание лота:</p> <p class="shortdescription">{{lot.description}}</p>
<p id="end_date" hidden="true">{{lot.end_date|date:"Y-m-d H:i"}}</p> <!--end_date используется для считывания даты скриптом-->
</div> <!--div lotdescription-->
</div> <!--div firstblock-->


<div id="secondblock" class="col-xs-4">
<div id='firstprice'>
<p>max цена:</p>
<p>{{lot.start_price}}</p>
</div> <!--div firstprice-->

<div id='categotyblock'>
  
</div> <!--div categoryblock-->  

<div id='cuerrentprice'>
<p>Последняя цена: 
{% if lot.current_price %}
<p id="current_price">{{lot.current_price|floatformat:2}}</p>
{% else %}
<p id="current_price">Ставок нет</p>
{% endif %}
</p>
</div> <!--div currentprice-->
</div> <!--div secondblock-->

</div> <!--div container contdiv-->

<div id='counter' class="col-xs-12">
<div id="countdown"></div>
<p id="note"></p>
</div> <!--div counter-->
<!--<div class='forbutton' id="makeabet" onclick=makeabet_2.js>
<!--<button id="makeabet">Сделать ставку</button><p id="help_for_bet"></p><br><br>
<h4>Сделать ставку!</h4>
</div>>-->

<div>
<button id="makeabet" class="btn">Сделать ставку</button>
</div>

{% if can_bet %}
{% endif %}
</div>     

</div>

      </div>
      {% endfor %}
      </div> 
<div class="row">      
<style>
   ul.pagination li {
    display: inline; /* Отображать как строчный элемент */
    margin-right: 5px; /* Отступ слева */
    padding: 3px; /* Поля вокруг текста */
   }
  </style>
<ul class="pagination" display="inline">
{% for p in paginator.page_range %}
  {% if p == page.number %}
    <li class="active">
  {% else %}
    <li>
  {% endif %}
    <a href="/category/{{category_id}}/?page={{ p }}">{{ p }}</a>
  </li>
{% endfor %}
</ul>  
</div>     
      
    
 

<body>
</body>
{% endblock %}

hollau/templates/editLot.html
{% extends 'base.html' %}
{% block javascript %}
	<link rel="stylesheet" type="text/css" href="/static/jquery.countdown.css">
	<link rel="stylesheet" type="text/css" href="/static/datetimepicker/jquery.datetimepicker.css"/>
	<script type="text/javascript" src="/static/script_section.js"></script>
	<script type="text/javascript" src="/static/js/jquery.countdown.js"></script>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'lot_edit' pk%}">
    {% csrf_token %}
    {{ form.as_p }}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p><input type="submit" value="OK"></p>
</form>
<script src="/static/datetimepicker/jquery.js"></script>
<script src="/static/datetimepicker/jquery.datetimepicker.full.js"></script>
<script>
    var test = $("p > input#id_start_date").text();
    console.log(test)
    $("[id='id_start_date']").parent().each(function (){
   		$(this).hide();
	});
    $("[id='id_end_date']").each(function (){ 
   		$(this).attr("id", "date2");
	});
    
</script>
<script src="/static/datetimepicker/datetime.js"></script>
{% endblock %}